# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: |
      curl -sSL https://install.python-poetry.org | python -
      poetry install
      
    command: poetry shell

