# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
image:
  file: .gitpod.Dockerfile

tasks:
  - before: /workspace/.pip-modules/bin/poetry install
  - init: /workspace/.pip-modules/bin/poetry shell

