name: Tests
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  tests:
    name: "tox"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade poetry tox tox-gh-actions

      - name: "Run Tests"
        run: python -m tox

      - name: "Upload coverage to coveralls.io"
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          debug: true

  coveralls-finish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Coveralls finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          debug: true
